### ISSUE TITLE
storage.delete is called each time when application is starting

### ISSUE THREAD

**Issue by katjai1** [flutterchina/cookie_jar#42]
By the reason of internal error inside PersistCookieJar class (type '_Map<dynamic, dynamic>' is not a subtype of type 'Map<String, Map<String, SerializableCookie>>')  all cookies deleted when application is starting

```
#0      PersistCookieJar._checkInitialized.<anonymous closure> (package:cookie_jar/src/persist_cookie_jar.dart:73:13)
#1      MapBase.map (dart:collection/maps.dart:82:28)
#2      PersistCookieJar._checkInitialized (package:cookie_jar/src/persist_cookie_jar.dart:54:32)
<asynchronous suspension>
#3      PersistCookieJar.loadForRequest (package:cookie_jar/src/persist_cookie_jar.dart:99:5)
<asynchronous suspension>
...

```

str value from file: 

```
{"dateamillionaire.com.pilot":{"/":{"ps_v2_local_session":"ps_v2_local_session=0f4een5vd4ttjb0iqmbvjmnfbi; Domain=dateamillionaire.com.pilot; Path=/;_crt=1685113197","pc_v1_local_lang":"pc_v1_local_lang=en; Expires=Sat, 29 Apr 2028 14:59:57 GMT; Max-Age=155520000; Domain=dateamillionaire.com.pilot; Path=/;_crt=1685113197"}}}
```

![image](https://github.com/flutterchina/cookie_jar/assets/98419164/d9acf1c5-c8d1-4517-bb80-e8d6b6ed092b)

**Comment by AlexV525** [comment]
Although the type cast issue was fixed, we still can explore not deleting the cookie instead.

**Comment by katjai1** [comment]
Thanks for the fast fix, everything is working well now!
